config/routes.rb
Rails.application.routes.draw do

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  resources :products

  resources :catgs

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  resources :wishlists

  get 'search', to: 'search#search'

  get "addwishlist" => "wishlists#addnew"

  root 'products#index'

end

app/models/catg.rb
class Catg < ActiveRecord::Base
	validates_presence_of :name
	has_many :products
end

app/controllers/catgs_controller.rb
class CatgsController < ApplicationController
  before_action :set_catg, only: [:show, :edit, :update, :destroy]

  # GET /catgs
  # GET /catgs.json
  def index
    @catgs = Catg.page(params[:page]).per(2)
  end

  # GET /catgs/1
  # GET /catgs/1.json
  def show
    @catg_products = Product.where(category: params[:id]).page(params[:page]).per(2)
  end

  # GET /catgs/new
  def new
    @catg = Catg.new
  end

  # GET /catgs/1/edit
  def edit
  end

  # POST /catgs
  # POST /catgs.json
  def create
    @catg = Catg.new(catg_params)

    respond_to do |format|
      if @catg.save
        format.html { redirect_to @catg, notice: 'Catg was successfully created.' }
        format.json { render :show, status: :created, location: @catg }
      else
        format.html { render :new }
        format.json { render json: @catg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catgs/1
  # PATCH/PUT /catgs/1.json
  def update
    respond_to do |format|
      if @catg.update(catg_params)
        format.html { redirect_to @catg, notice: 'Catg was successfully updated.' }
        format.json { render :show, status: :ok, location: @catg }
      else
        format.html { render :edit }
        format.json { render json: @catg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catgs/1
  # DELETE /catgs/1.json
  def destroy
    @catg.destroy
    respond_to do |format|
      format.html { redirect_to catgs_url, notice: 'Catg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catg
      @catg = Catg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catg_params
      params.require(:catg).permit(:name, :nop)
    end
end

app/helpers/catgs_helper.rb
module CatgsHelper
	def prod_count(catgid)
		@prod_count = Product.where(category: catgid).count
		return @prod_count
	end
end

app/views/catgs/_form.html.erb
<div class="container">     
<div class="col-md-5 col-md-offset-3">
<div class="row">
<%= form_for @catg, :html => { :class => "form-horizontal catg" } do |f| %>

    <% if @catg.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@catg.errors.count, "error") %> prohibited this catg from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @catg.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%#= error_span(@catg[:name]) %>
  </div>
  
  <br/>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            catgs_path, :class => 'btn btn-default' %>

<% end %>
</div>
</div>
</div>

app/views/catgs/edit.html.erb
<%- model_class = Catg -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/catgs/index.html.erb
<%- model_class = Catg -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= page_entries_info @catgs %>
<hr/>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:nop) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @catgs.each do |catg| %>
      <tr>
        <td><%= link_to catg.id, catg_path(catg) %></td>
        <td><%= catg.name %></td>
        <td><%= prod_count(catg.id) %></td>
        <td><%=l catg.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_catg_path(catg), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      catg_path(catg),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>
<%= paginate @catgs,:theme => 'twitter-bootstrap' %>
<br/>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_catg_path,
            :class => 'btn btn-primary' %>

app/views/catgs/new.html.erb
<%- model_class = Catg -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/catgs/show.html.erb
<%- model_class = Catg -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @catg.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nop) %>:</strong></dt>
  <dd><%= prod_count(@catg.id) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              catgs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_catg_path(@catg), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              catg_path(@catg),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<hr/>
<%= page_entries_info @catg_products %>
<hr/>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= "Dis(%)" %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:instock) %></th>
      <th><%= "Picture" %></th>
      <th><%= "Created" %></th>
    </tr>
  </thead>
  <tbody>
    <% @catg_products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.discount %></td>
        <td><%= product.description %></td>
        <td><%= product.category %></td>
        <td><%= product.instock %></td>
        <td><%= image_tag product.avatar.url(:thumb) %></td>
        <td><%= time_ago_in_words(product.created_at) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @catg_products,:theme => 'twitter-bootstrap' %>