config/routes.rb
Rails.application.routes.draw do

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  resources :products

  resources :catgs

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  resources :wishlists

  get 'search', to: 'search#search'

  get "addwishlist" => "wishlists#addnew"

  root 'products#index'

end

app/models/product.rb
require 'elasticsearch/model'
class Product < ActiveRecord::Base
	has_many :order_items
	has_attached_file :avatar, :styles => {:large => "350x350>", :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	belongs_to :catgs
  	belongs_to :wishlists
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  	validates_presence_of :name, :price, :discount, :description, :category,:instock,:avatar


  	# default_scope { where(active: true) }

  	include Elasticsearch::Model
  	include Elasticsearch::Model::Callbacks

end

Product.import # for auto sync model with elastic search

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index

    @products = Product.all
    @order_item = current_order.order_items.new
    @products = Product.page(params[:page]).per(2)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :discount, :description,:category,:instock,:avatar)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def catg_name(catgid)
		@catg_name = Catg.where(id: catgid).pluck(:name).first
		return @catg_name
	end
end

app/views/products/_form.html.erb
<div class="container">     
<div class="col-md-5 col-md-offset-3">
<div class="row">
<%= form_for @product, :html => { :class => "form-horizontal product", :multipart => true  } do |f| %>

    <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%#= error_span(@product[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%#= error_span(@product[:price]) %>
  </div>
  <div class="control-group">
    <%= f.label :discount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :discount, :class => 'form-control' %>
    </div>
    <%#= error_span(@product[:discount]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%#= error_span(@product[:description]) %>
  </div>
   <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'form-control' %>
    </div>
    <%#= error_span(@product[:instock]) %>
  </div>
  <div class="control-group">
    <%= f.label :instock, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :instock, :class => 'form-control' %>
    </div>
    <%#= error_span(@product[:instock]) %>
  </div>
  
  <%= f.label :avatar, :class => 'control-label' %>
    
  <%= f.file_field :avatar, :class => 'form-control' %>
    
    <%#= error_span(@catg[:nop]) %>
  
<br/>
<br/>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            products_path, :class => 'btn btn-default' %>

<% end %>
</div>
</div>
</div>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<!--
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= page_entries_info @products %>
<hr/>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= "Dis(%)" %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:instock) %></th>
      <th><%= "Picture" %></th>
      <th><%= "Created" %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      

    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.discount %></td>
        <td><%= product.description %></td>
        <td><%= product.category %></td>
        <td><%= product.instock %></td>
        <td><%= image_tag product.avatar.url(:thumb) %></td>
        <td><%= time_ago_in_words(product.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>

        </td>
        <td>
        
        </td>
      </tr>
    <% end %>
    
  </tbody>
</table>
<hr/>
<%= paginate @products,:theme => 'twitter-bootstrap' %>
<br/>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>
-->
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<!--
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount) %>:</strong></dt>
  <dd><%= @product.discount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= catg_name(@product.category) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:instock) %>:</strong></dt>
  <dd><%= @product.instock %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= image_tag @product.avatar.url(:thumb)%></dd>
<dd>
  <%#= link_to "Wishlist",addwishlist_path(@product.name), :class => 'btn btn-success btn-xs' %>
  <%= form_for [Wishlist.new] do |f| %>
  <div><%= hidden_field_tag :itemid, @product.id %></div>
  <%= f.submit "Add to Wishlist", class: "btn btn-success" %>
<% end %></dd>

</dl>
-->
<div class="row">
        <div class="col-md-3 col-md-offset-1" style="height: 400px;">
            <%= image_tag @product.avatar.url(:large)%>
        </div>
        <div class="col-md-6 col-md-offset-1" style="height: 400px;">
            <h1><%= @product.name %></h1>
            <hr>
            <div class="row">
                <div class="col-md-10">
                    <p class="text-justify">
                        <%= @product.description %>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4" style="height: 100px;">
                    <h3><%= @product.price %><br/>
                    <small><%= @product.discount %>% OFF</small></h3>
                </div>
                <div class="col-md-8" style="height: 20px;">
                </div>
                <div class="col-md-8">
                    <button type="button" class="btn btn-primary btn-lg">Add to Cart</button>
                    <button type="button" class="btn btn-success btn-lg">Buy Now</button>
                </div>
            </div>
        </div>
    </div>


<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>